main: me.schooltests.collectionhoppers.CollectionHoppers
name: CollectionHoppers
author: SchoolTests
version: 1.0
commands:
  getHopperWand:
    usage: /gethopperwand
    description: Give's user a hopper wand
  hopperinfo:
    usage: /hopperinfo
    description: Give's users information about CollectionHoppers
    aliases: [hi]